# Generated by Django 5.0.1 on 2024-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_name', models.CharField(max_length=300)),
                ('Bed_id', models.CharField(max_length=300, unique=True)),
                ('Ward_number', models.CharField(max_length=100)),
                ('Room_number', models.CharField(max_length=100)),
                ('Bed_type', models.CharField(max_length=300)),
            ],
        ),
    ]
