# Generated by Django 5.0.1 on 2024-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=300)),
                ('hospital_image', models.ImageField(upload_to='hospital_images')),
                ('hospital_address', models.TextField()),
                ('hospital_details', models.TextField()),
            ],
        ),
    ]
