# Generated by Django 5.0.1 on 2024-04-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_beds_bed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
