# Generated by Django 5.0.1 on 2024-03-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_beds_disease_alter_beds_room_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beds',
            name='Disease',
        ),
    ]
