# Generated by Django 5.0.1 on 2024-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_filldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='Bed_id',
            field=models.CharField(max_length=300),
        ),
    ]
