# Generated by Django 5.0.1 on 2024-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_beds_bed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='Bed_id',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
